-- 코드를 입력하세요
SELECT C.ANIMAL_ID, C.NAME FROM 
    (SELECT A.ANIMAL_ID, A.NAME, (B.DATETIME - A.DATETIME) DATETIME
    FROM ANIMAL_INS A, ANIMAL_OUTS B
    WHERE A.ANIMAL_ID = B.ANIMAL_ID
    ORDER BY DATETIME DESC) C
WHERE ROWNUM<=2;