SELECT 
A.USER_ID
,A.NICKNAME
,B.TOTAL_SALES
FROM USED_GOODS_USER A,
    (SELECT WRITER_ID
    ,SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID, STATUS
    HAVING SUM(PRICE) >= 700000 AND STATUS='DONE'
    ) B
WHERE A.USER_ID = B.WRITER_ID
ORDER BY B.TOTAL_SALES
