-- SELECT 
-- SUBSTR(PRICE,1,1)*10000 AS PRICE_GROUP,
-- COUNT(*) AS RPODUCTS
-- FROM PRODUCT
-- GROUP BY SUBSTR(PRICE,1,1)*10000
-- ORDER BY SUBSTR(PRICE,1,1)*10000

SELECT 
PRICE_GROUP,
COUNT(PRICE_GROUP) AS RPODUCTS
FROM (SELECT SUBSTR(PRICE,1,1)*10000 AS PRICE_GROUP FROM PRODUCT)
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP